name: CI

on:
  schedule:
    - cron: '*/5 * * * *'

  workflow_dispatch:
    inputs:
      feature_flags_test:
        description: 'Define feature flags for the TEST deployment. If you do not use any feature flags, please let only just feature-flags:'
        required: false
        default: 'feature-flags: EnableCollaborationNotifications'

env:
  feature_flags_test: ${{ github.event.inputs.feature_flags_test || "feature-flags: EnableCollaborationNotifications" }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          echo ${{ inputs.feature_flags_test }}
