name: Checkout Repository
on: [pull_request, issue_comment]

jobs:
    checkout:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

    print_text:
        env: Production
        runs-on: ubuntu-latest

        steps:
        - name: Print TEXT
          run: |
              echo "TEXT"
              
    print_text2:
        runs-on: ubuntu-latest

        steps:
        - name: Print TEXT2
          run: echo "TEXT2"
